[phases.setup]
nixPkgs = ["nodejs-18_x", "npm", "python3", "gcc"]

[phases.install]
cmds = [
    "npm ci",
    "npm rebuild better-sqlite3 || true"
]

[phases.build]
cmds = [
    "npm run rebuild-sqlite || true",
    "node src/services/database.js || true"
]

[start]
cmd = "node src/app.js"